export function formatFieldLabel(fieldName: string): string {
  const overrides: Record<string, string> = {
    'patient_id': 'Patient ID',
    'name': 'Name',
    'phone': 'Phone',
    'email': 'Email',
    'birth_date': 'Date of Birth',
    'age_years': 'Age (years)',
    'sex_at_birth': 'Sex at Birth',
    'height_cm': 'Height (cm)',
    'weight_kg': 'Weight (kg)',
    'bmi': 'BMI',
    'sbp': 'Systolic BP',
    'dbp': 'Diastolic BP',
    'smoking_status': 'Smoking Status',
    'pack_years': 'Pack Years',
    'diabetes_dx': 'Diabetes Diagnosis',
    'diabetes_type': 'Diabetes Type',
    'a1c_pct_recent': 'Recent A1C (%)',
    'a1c_date': 'A1C Date',
    'ckd_stage': 'CKD Stage',
    'egfr_ml_min_1_73m2_recent': 'Recent eGFR (mL/min/1.73m²)',
    'egfr_date': 'eGFR Date',
    'alt_u_l': 'ALT (U/L)',
    'ast_u_l': 'AST (U/L)',
    'bilirubin_mg_dl': 'Bilirubin (mg/dL)',
    'mi_history': 'MI History',
    'stroke_tia_history': 'Stroke/TIA History',
    'pad_history': 'PAD History',
    'hf_history': 'Heart Failure History',
    'lvef_pct': 'LVEF (%)',
    'lvef_date': 'LVEF Date',
    'nyha_class': 'NYHA Class',
    'statin_current': 'Current Statin Use',
    'anticoagulant_current': 'Current Anticoagulant Use',
    'sglt2_current': 'Current SGLT2 Use',
    'glp1_current': 'Current GLP-1 Use',
    'insulin_current': 'Current Insulin Use',
    'ntprobnp_pg_ml': 'NT-proBNP (pg/mL)',
    'troponin_ng_l': 'Troponin (ng/L)',
    'active_cancer': 'Active Cancer',
    'cancer_primary_site': 'Cancer Primary Site',
    'cancer_stage': 'Cancer Stage',
    'treatment_status': 'Treatment Status',
    'last_treatment_type': 'Last Treatment Type',
    'last_treatment_date': 'Last Treatment Date',
    'ecog_status': 'ECOG Status',
    'has_measurable_disease_recist': 'Measurable Disease (RECIST)',
    'anc_10e9_l': 'ANC (×10⁹/L)',
    'hemoglobin_g_dl': 'Hemoglobin (g/dL)',
    'platelets_10e9_l': 'Platelets (×10⁹/L)',
    'qtc_ms_recent': 'Recent QTc (ms)',
    'pregnancy_status': 'Pregnancy Status',
    'qualified_disease': 'Qualified Disease',
    'last_contacted': 'Last Contacted',
    'status': 'Status',
  };

  return overrides[fieldName.toLowerCase()] || fieldName
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}
