import { Patient } from '@/types/patient';

export const mockPatients: Patient[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    age: 45,
    diagnosis: 'Type 2 Diabetes',
    medications: ['Metformin', 'Lisinopril'],
    testResults: {
      bloodPressure: '130/85',
      cholesterol: '195 mg/dL',
      glucose: '145 mg/dL',
    },
    status: 'eligible',
    score: 92,
    email: 'sarah.j@email.com',
    phone: '(555) 123-4567',
    eligibilityCriteria: {
      ageRange: true,
      diagnosisMatch: true,
      noContraindications: true,
      labResultsNormal: true,
      informedConsent: true,
    },
    notes: 'Highly motivated patient, expressed strong interest in trial participation.',
    lastContact: '2024-10-15',
    createdAt: '2024-10-01',
  },
  {
    id: '2',
    name: 'Michael Chen',
    age: 62,
    diagnosis: 'Hypertension',
    medications: ['Amlodipine', 'Atorvastatin', 'Aspirin'],
    testResults: {
      bloodPressure: '145/92',
      cholesterol: '220 mg/dL',
      glucose: '98 mg/dL',
    },
    status: 'needs_review',
    score: 75,
    email: 'm.chen@email.com',
    phone: '(555) 234-5678',
    eligibilityCriteria: {
      ageRange: true,
      diagnosisMatch: true,
      noContraindications: true,
      labResultsNormal: false,
      informedConsent: false,
    },
    notes: 'BP slightly elevated, needs follow-up labs.',
    lastContact: '2024-10-16',
    createdAt: '2024-10-03',
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    age: 38,
    diagnosis: 'Asthma',
    medications: ['Albuterol', 'Fluticasone'],
    testResults: {
      bloodPressure: '118/76',
      cholesterol: '175 mg/dL',
      other: { 'Peak Flow': '380 L/min' },
    },
    status: 'eligible',
    score: 88,
    email: 'e.rodriguez@email.com',
    phone: '(555) 345-6789',
    eligibilityCriteria: {
      ageRange: true,
      diagnosisMatch: true,
      noContraindications: true,
      labResultsNormal: true,
      informedConsent: true,
    },
    notes: 'Well-controlled asthma, excellent candidate.',
    lastContact: '2024-10-17',
    createdAt: '2024-10-05',
  },
  {
    id: '4',
    name: 'Robert Williams',
    age: 71,
    diagnosis: 'COPD',
    medications: ['Tiotropium', 'Budesonide', 'Prednisone'],
    testResults: {
      bloodPressure: '138/88',
      other: { 'FEV1': '52%', 'O2 Saturation': '91%' },
    },
    status: 'ineligible',
    score: 45,
    email: 'r.williams@email.com',
    phone: '(555) 456-7890',
    eligibilityCriteria: {
      ageRange: false,
      diagnosisMatch: true,
      noContraindications: false,
      labResultsNormal: false,
      informedConsent: false,
    },
    notes: 'Age exceeds trial limit, current steroid use is exclusion criterion.',
    lastContact: '2024-10-14',
    createdAt: '2024-09-28',
  },
  {
    id: '5',
    name: 'Jennifer Martinez',
    age: 29,
    diagnosis: 'Migraine',
    medications: ['Sumatriptan', 'Topiramate'],
    testResults: {
      bloodPressure: '115/72',
      cholesterol: '165 mg/dL',
    },
    status: 'pending',
    score: 0,
    email: 'j.martinez@email.com',
    phone: '(555) 567-8901',
    eligibilityCriteria: {
      ageRange: true,
      diagnosisMatch: true,
      noContraindications: true,
      labResultsNormal: true,
      informedConsent: false,
    },
    notes: 'Initial screening complete, awaiting lab results.',
    lastContact: '2024-10-18',
    createdAt: '2024-10-10',
  },
  {
    id: '6',
    name: 'David Thompson',
    age: 55,
    diagnosis: 'Type 2 Diabetes',
    medications: ['Insulin Glargine', 'Metformin', 'Sitagliptin'],
    testResults: {
      bloodPressure: '142/90',
      cholesterol: '210 mg/dL',
      glucose: '168 mg/dL',
    },
    status: 'needs_review',
    score: 68,
    email: 'd.thompson@email.com',
    phone: '(555) 678-9012',
    eligibilityCriteria: {
      ageRange: true,
      diagnosisMatch: true,
      noContraindications: true,
      labResultsNormal: false,
      informedConsent: true,
    },
    notes: 'HbA1c levels need verification before final approval.',
    lastContact: '2024-10-16',
    createdAt: '2024-10-07',
  },
];

export function generateRandomScore(): number {
  return Math.floor(Math.random() * 50) + 50;
}
